"""empty message

Revision ID: 2e06b0732814
Revises: f4274185ff0e
Create Date: 2025-11-14 19:11:05.322372

"""
from typing import Sequence, Union

from alembic import op
import sqlalchemy as sa


# revision identifiers, used by Alembic.
revision: str = '2e06b0732814'
down_revision: Union[str, Sequence[str], None] = 'f4274185ff0e'
branch_labels: Union[str, Sequence[str], None] = None
depends_on: Union[str, Sequence[str], None] = None


def upgrade() -> None:
    """Upgrade schema."""
    # ### commands auto generated by Alembic - please adjust! ###
    op.add_column('paper', sa.Column('community', sa.Integer(), nullable=True))
    # ### end Alembic commands ###


def downgrade() -> None:
    """Downgrade schema."""
    # ### commands auto generated by Alembic - please adjust! ###
    op.drop_column('paper', 'community')
    # ### end Alembic commands ###
