"""empty message

Revision ID: 667259e05057
Revises: 2e06b0732814
Create Date: 2025-11-25 09:17:02.314407

"""
from typing import Sequence, Union

from alembic import op
import sqlalchemy as sa


# revision identifiers, used by Alembic.
revision: str = '667259e05057'
down_revision: Union[str, Sequence[str], None] = '2e06b0732814'
branch_labels: Union[str, Sequence[str], None] = None
depends_on: Union[str, Sequence[str], None] = None


def upgrade() -> None:
    """Upgrade schema."""
    # ### commands auto generated by Alembic - please adjust! ###
    op.create_table('citation',
    sa.Column('id', sa.Integer(), nullable=False),
    sa.Column('citing_paper_doi', sa.Integer(), nullable=False),
    sa.Column('cited_paper_doi', sa.Integer(), nullable=False),
    sa.ForeignKeyConstraint(['cited_paper_doi'], ['paper.doi'], ),
    sa.ForeignKeyConstraint(['citing_paper_doi'], ['paper.doi'], ),
    sa.PrimaryKeyConstraint('id')
    )
    op.add_column('paper', sa.Column('citation_count', sa.Integer(), nullable=True))
    # ### end Alembic commands ###


def downgrade() -> None:
    """Downgrade schema."""
    # ### commands auto generated by Alembic - please adjust! ###
    op.drop_column('paper', 'citation_count')
    op.drop_table('citation')
    # ### end Alembic commands ###
