"""empty message

Revision ID: ff41682c72cd
Revises: 667259e05057
Create Date: 2025-11-25 09:58:34.016817

"""
from typing import Sequence, Union

from alembic import op
import sqlalchemy as sa


# revision identifiers, used by Alembic.
revision: str = 'ff41682c72cd'
down_revision: Union[str, Sequence[str], None] = '667259e05057'
branch_labels: Union[str, Sequence[str], None] = None
depends_on: Union[str, Sequence[str], None] = None


def upgrade() -> None:
    """Upgrade schema."""
    # ### commands auto generated by Alembic - please adjust! ###
    op.add_column('paper', sa.Column('citations_fetched', sa.Boolean(), nullable=True))
    # ### end Alembic commands ###


def downgrade() -> None:
    """Downgrade schema."""
    # ### commands auto generated by Alembic - please adjust! ###
    op.drop_column('paper', 'citations_fetched')
    # ### end Alembic commands ###
