"""empty message

Revision ID: 17cb4435691a
Revises: 5c08f8735b33
Create Date: 2025-11-14 12:52:31.144980

"""
from typing import Sequence, Union

from alembic import op
import sqlalchemy as sa


# revision identifiers, used by Alembic.
revision: str = '17cb4435691a'
down_revision: Union[str, Sequence[str], None] = '5c08f8735b33'
branch_labels: Union[str, Sequence[str], None] = None
depends_on: Union[str, Sequence[str], None] = None


def upgrade() -> None:
    """Upgrade schema."""
    # ### commands auto generated by Alembic - please adjust! ###
    op.add_column('papers', sa.Column('abstract', sa.Text(), nullable=True))
    op.add_column('papers', sa.Column('keywords', sa.Text(), nullable=True))
    # ### end Alembic commands ###


def downgrade() -> None:
    """Downgrade schema."""
    # ### commands auto generated by Alembic - please adjust! ###
    op.drop_column('papers', 'keywords')
    op.drop_column('papers', 'abstract')
    # ### end Alembic commands ###
